# Generated by Django 5.0.4 on 2024-05-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_managers_remove_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True), max_length=254),
        ),
    ]
