# Generated by Django 5.0.4 on 2024-05-14 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconfirmstring',
            old_name='u_account',
            new_name='username',
        ),
    ]
