# Generated by Django 4.2.13 on 2024-05-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_email_alter_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='line_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
