# Generated by Django 4.2.13 on 2024-05-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_line_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nonce',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
