# Generated by Django 5.0.4 on 2024-04-17 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('account', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('c_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('c_type', models.CharField(max_length=2)),
                ('c_name', models.CharField(max_length=50)),
                ('c_icon', models.CharField(max_length=200)),
                ('u_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_category', to='accounting.customuser')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('e_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('e_date', models.DateField()),
                ('e_type', models.CharField(max_length=2)),
                ('e_amount', models.FloatField()),
                ('e_desc', models.CharField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_expenses', to='accounting.category')),
                ('u_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_expenses', to='accounting.customuser')),
            ],
            options={
                'db_table': 'expenses',
            },
        ),
    ]
