# Generated by Django 5.0.4 on 2024-04-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('c_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('c_type', models.CharField(max_length=2)),
                ('c_name', models.CharField(max_length=50)),
                ('c_icon', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('e_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('c_id', models.IntegerField()),
                ('e_date', models.DateField()),
                ('e_type', models.CharField(max_length=2)),
                ('e_amount', models.FloatField()),
                ('e_desc', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'expenses',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
