# Generated by Django 5.0.4 on 2024-05-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('c_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('c_type', models.CharField(max_length=2)),
                ('c_name', models.CharField(max_length=50)),
                ('c_icon', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tb_category',
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('e_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('e_date', models.DateField()),
                ('e_type', models.CharField(max_length=2)),
                ('e_amount', models.FloatField()),
                ('e_desc', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'tb_expenses',
            },
        ),
    ]
