# Generated by Django 5.0.4 on 2024-04-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='line_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
