# Generated by Django 5.0.4 on 2024-05-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='u_account',
            new_name='u_username',
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='u_account',
            new_name='u_username',
        ),
    ]
