# Generated by Django 5.0.4 on 2024-05-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
