# Generated by Django 5.0.4 on 2024-05-15 06:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_rename_u_username_category_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='expenses',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
