# Generated by Django 5.0.4 on 2024-05-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_category_create_time_expenses_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='e_desc',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
