# Generated by Django 5.0.4 on 2024-05-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_userconfirmstring'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconfirmstring',
            old_name='user',
            new_name='u_account',
        ),
        migrations.AlterField(
            model_name='userconfirmstring',
            name='code',
            field=models.CharField(max_length=2000),
        ),
    ]
